import { MainNav } from '@/components/main-nav'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Axie Spy',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`text-white bg-zinc-950 ${inter.className}`}>
     
      <MainNav className="mx-6" />
      <main className="flex justify-center mt-20">{children}
      </main>
      </body>
    </html>
  )
}
